# this first block is copied from https://github.com/leanprover/lean/blob/master/.travis.yml

language: cpp
sudo: true
cache: apt
addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:kalakris/cmake' # cmake 2.8 for precise
      - sourceline: 'ppa:adrozdoff/cmake' # cmake 3 for trusty
      - sourceline: 'ppa:h-rayflood/llvm'
      - sourceline: ppa:hvr/z3   # z3 for the smt interface package
    packages: &default_packages
      - cmake
      - libgmp-dev
      - libgoogle-perftools-dev
      - g++-4.9
      - clang-3.4

dist: precise
env:
       CMAKE_CXX_COMPILER=g++-4.9

install:
  - git clone https://github.com/leanprover/lean.git ../lean
  - cd ../lean && mkdir -p build/release && cd build/release && cmake -DCMAKE_CXX_COMPILER=$CMAKE_CXX_COMPILER ../../src && make
  - export PATH=../lean/bin:$PATH
  - cd ../lean-tidy

script:
  - leanpkg test