[package]
name = "lean-tidy"
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "5df2ee70cfd576e6fa11359496a8a06c029151c9"}
