[package]
name = "lean-tidy"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "d84af03bdb8ec4e02c96b6262e7b78c8f3de412b"}
