[package]
name = "lean-tidy"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "c75b07219b45c6c46b9f1e9beca9129fb94cce57"}
